# Generated by Django 3.2.16 on 2022-12-13 03:15

import logging
import types

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.utils import OperationalError


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminAPIAllowListConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(max_length=64, verbose_name="创建者")),
                ("updater", models.CharField(max_length=64, verbose_name="更新者")),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
                (
                    "api",
                    models.CharField(
                        choices=[
                            ("system_list", "获取系统列表"),
                            ("group_list", "获取用户组列表"),
                            ("group_member_list", "获取用户组成员列表"),
                            ("subject_joined_group_list", "获取Subject加入的用户组列表"),
                            ("subject_role_list", "获取Subject角色列表"),
                            ("role_super_manager_member_list", "获取超级管理员成员列表"),
                            ("role_system_manager_member_list", "获取系统管理员及成员列表"),
                            ("audit_event_list", "获取审计事件列表"),
                            ("subject_freeze_unfreeze", "冻结/解冻Subject"),
                            ("subject_permission_cleanup", "权限清理"),
                            ("subject_permission_exists", "权限是否存在"),
                        ],
                        help_text="*代表任意",
                        max_length=32,
                        verbose_name="API",
                    ),
                ),
                ("app_code", models.CharField(max_length=32, verbose_name="API调用者")),
            ],
            options={
                "verbose_name": "Admin API允许的应用白名单",
                "verbose_name_plural": "Admin API允许的应用白名单",
                "db_table": "api.admin_adminapiallowlistconfig",
                "ordering": ["-id"],
                "unique_together": {("app_code", "api")},
            },
        ),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        def execute(self, sql, params=()):
            try:
                BaseDatabaseSchemaEditor.execute(self, sql, params)
            except OperationalError:
                logging.warning("create table api.admin_adminapiallowlistconfig error", exc_info=True)

        schema_editor.execute = types.MethodType(execute, schema_editor)

        return super().apply(project_state, schema_editor, collect_sql)
