# Generated by Django 3.2.16 on 2024-03-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminapiallowlistconfig',
            name='api',
            field=models.CharField(choices=[('system_list', '获取系统列表'), ('group_list', '获取用户组列表'), ('group_member_list', '获取用户组成员列表'), ('subject_joined_group_list', '获取Subject加入的用户组列表'), ('subject_role_list', '获取Subject角色列表'), ('role_super_manager_member_list', '获取超级管理员成员列表'), ('role_system_manager_member_list', '获取系统管理员及成员列表'), ('audit_event_list', '获取审计事件列表'), ('subject_freeze_unfreeze', '冻结/解冻Subject'), ('subject_permission_cleanup', '权限清理'), ('subject_permission_exists', '权限是否存在'), ('grade_manager_list', '获取分级管理员列表'), ('grade_manager_create', '新建分级管理员'), ('grade_manager_update', '更新分级管理员')], help_text='*代表任意', max_length=32, verbose_name='API'),
        ),
        migrations.CreateModel(
            name='SystemAllowAuthSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('system_id', models.CharField(max_length=32, verbose_name='接入系统')),
                ('auth_system_id', models.CharField(help_text='*代表任意', max_length=32, verbose_name='接入系统')),
            ],
            options={
                'verbose_name': '系统允许授权的系统',
                'verbose_name_plural': '系统允许授权的系统',
                'ordering': ['-id'],
                'index_together': {('system_id', 'auth_system_id')},
            },
        ),
    ]
