# Generated by Django 2.2.24 on 2022-01-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api.admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='adminapiallowlistconfig',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='adminapiallowlistconfig',
            unique_together={('app_code', 'api')},
        ),

    ]
