# Generated by Django 2.2.24 on 2022-03-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_groupsaasattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='readonly',
            field=models.BooleanField(default=False, verbose_name='用户组只读标识'),
        ),
    ]
