# Generated by Django 2.2.28 on 2022-11-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_group_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='source_system_id',
            field=models.CharField(default='', max_length=32),
        ),
    ]
