# Generated by Django 2.2.24 on 2022-06-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_group_readonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsAddMemberDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('record_id', models.IntegerField(verbose_name='批量添加成员操作记录ID')),
                ('group_id', models.IntegerField(verbose_name='用户组ID')),
                ('members', models.TextField(verbose_name='成员')),
                ('status', models.CharField(choices=[('succeed', '添加成员成功'), ('failed', '添加成员失败')], default='failed', max_length=16, verbose_name='状态')),
                ('error_info', models.TextField(default='', verbose_name='异常信息')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupsAddMemberRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('operator', models.CharField(max_length=16, verbose_name='操作者')),
                ('status', models.CharField(choices=[('succeed', '添加成员成功'), ('failed', '添加成员失败'), ('partial_failed', '部分失败')], default='failed', max_length=16, verbose_name='状态')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
