# Generated by Django 3.2.16 on 2023-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_alter_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='apply_able',
            field=models.BooleanField(default=True, verbose_name='用户组可申请'),
        ),
    ]
