# Generated by Django 3.2.16 on 2023-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
