# Generated by Django 3.2.16 on 2023-08-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_alter_group_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='apply_able',
            field=models.BooleanField(db_index=True, default=True, verbose_name='用户组可申请'),
        ),
    ]
