# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("group", "0016_group_apply_disable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupsaasattribute",
            options={"verbose_name": "用户组 SaaS 属性", "verbose_name_plural": "用户组 SaaS 属性"},
        ),
        migrations.AddField(
            model_name="group",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="groupauthorizelock",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="groupsaasattribute",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="groupauthorizelock",
            name="group_id",
            field=models.IntegerField(verbose_name="用户组 ID"),
        ),
        migrations.AlterField(
            model_name="groupauthorizelock",
            name="system_id",
            field=models.CharField(max_length=32, verbose_name="系统 ID"),
        ),
        migrations.AlterField(
            model_name="groupauthorizelock",
            name="template_id",
            field=models.IntegerField(verbose_name="模板 ID"),
        ),
        migrations.AlterField(
            model_name="groupsaasattribute",
            name="group_id",
            field=models.IntegerField(verbose_name="用户组 ID"),
        ),
        migrations.AlterField(
            model_name="groupsaasattribute",
            name="key",
            field=models.CharField(max_length=32, verbose_name="属性的 Key"),
        ),
        migrations.AlterField(
            model_name="groupsaasattribute",
            name="value",
            field=models.CharField(default="", max_length=64, verbose_name="属性的 value"),
        ),
    ]
