# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.16 on 2020-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProcessRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('system_id', models.CharField(max_length=32, verbose_name='系统ID')),
                ('action_id', models.CharField(max_length=32, verbose_name='操作ID')),
                ('process_id', models.IntegerField(verbose_name='审批流程ID')),
            ],
            options={
                'verbose_name': '操作与审批流程关联',
                'verbose_name_plural': '操作与审批流程关联',
            },
        ),
        migrations.CreateModel(
            name='ApprovalProcessGlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('application_type', models.CharField(choices=[('grant_action', '自定义权限申请'), ('join_group', '加入用户组'), ('join_rating_manager', '加入分级管理员'), ('create_rating_manager', '创建或分级管理员'), ('update_rating_manager', '修改分级管理员')], max_length=32, verbose_name='申请类型')),
                ('process_id', models.IntegerField(verbose_name='审批流程ID')),
            ],
            options={
                'verbose_name': '审批流程全局配置',
                'verbose_name_plural': '审批流程全局配置',
            },
        ),
        migrations.CreateModel(
            name='GroupProcessRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('group_id', models.IntegerField(verbose_name='用户组ID')),
                ('process_id', models.IntegerField(verbose_name='审批流程ID')),
            ],
            options={
                'verbose_name': '用户组与审批流程关联',
                'verbose_name_plural': '用户组与审批流程关联',
            },
        ),
    ]
