# Generated by Django 3.2.16 on 2022-12-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20201217_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalprocessglobalconfig',
            name='application_type',
            field=models.CharField(choices=[('grant_action', '自定义权限申请'), ('renew_action', '自定义权限续期'), ('join_group', '加入用户组'), ('renew_group', '用户组续期'), ('join_rating_manager', '加入分级管理员'), ('create_rating_manager', '创建分级管理员'), ('update_rating_manager', '修改分级管理员'), ('grant_temporary_action', '临时权限申请')], max_length=32, unique=True, verbose_name='申请类型'),
        ),
        migrations.AlterUniqueTogether(
            name='groupprocessrelation',
            unique_together={('group_id',)},
        ),
    ]
