# Generated by Django 4.2 on 2025-03-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_auto_20231016_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionprocessrelation',
            name='sensitivity_level',
            field=models.CharField(choices=[('L1', '不敏感'), ('L2', '低'), ('L3', '中'), ('L4', '高'), ('L5', '极高')], default='L1', max_length=32, verbose_name='敏感等级'),
        ),
    ]
