# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0005_alter_actionprocessrelation_sensitivity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionprocessrelation",
            name="tenant_id",
            field=models.CharField(default="", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="approvalprocessglobalconfig",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="groupprocessrelation",
            name="tenant_id",
            field=models.CharField(default="", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="actionprocessrelation",
            name="action_id",
            field=models.CharField(max_length=32, verbose_name="操作 ID"),
        ),
        migrations.AlterField(
            model_name="actionprocessrelation",
            name="process_id",
            field=models.CharField(max_length=128, verbose_name="审批流程 ID"),
        ),
        migrations.AlterField(
            model_name="actionprocessrelation",
            name="system_id",
            field=models.CharField(max_length=32, verbose_name="系统 ID"),
        ),
        migrations.AlterField(
            model_name="approvalprocessglobalconfig",
            name="application_type",
            field=models.CharField(
                choices=[
                    ("grant_action", "自定义权限申请"),
                    ("renew_action", "自定义权限续期"),
                    ("join_group", "加入用户组"),
                    ("renew_group", "用户组续期"),
                    ("join_rating_manager", "加入管理空间"),
                    ("create_rating_manager", "创建管理空间"),
                    ("update_rating_manager", "修改管理空间"),
                    ("grant_temporary_action", "临时权限申请"),
                ],
                max_length=32,
                verbose_name="申请类型",
            ),
        ),
        migrations.AlterField(
            model_name="approvalprocessglobalconfig",
            name="process_id",
            field=models.CharField(max_length=128, verbose_name="审批流程 ID"),
        ),
        migrations.AlterField(
            model_name="groupprocessrelation",
            name="group_id",
            field=models.IntegerField(verbose_name="用户组 ID"),
        ),
        migrations.AlterField(
            model_name="groupprocessrelation",
            name="process_id",
            field=models.CharField(max_length=128, verbose_name="审批流程 ID"),
        ),
        migrations.AlterUniqueTogether(
            name="approvalprocessglobalconfig",
            unique_together={("tenant_id", "application_type")},
        ),
    ]
