# Generated by Django 4.2.20 on 2025-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0005_alter_actionprocessrelation_sensitivity_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionprocessrelation",
            name="process_id",
            field=models.CharField(max_length=32, verbose_name="审批流程ID"),
        ),
        migrations.AlterField(
            model_name="approvalprocessglobalconfig",
            name="process_id",
            field=models.CharField(max_length=32, verbose_name="审批流程ID"),
        ),
        migrations.AlterField(
            model_name="groupprocessrelation",
            name="process_id",
            field=models.CharField(max_length=32, verbose_name="审批流程ID"),
        ),
    ]
