# Generated by Django 4.2.19 on 2025-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("temporary_policy", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="temporarypolicy",
            new_name="temporary_p_subject_364fe2_idx",
            old_fields=("subject_id", "subject_type", "system_id"),
        ),
    ]
