# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "temporary_policy",
            "0002_rename_temporarypolicy_subject_id_subject_type_system_id_temporary_p_subject_364fe2_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarypolicy",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="temporarypolicy",
            name="action_id",
            field=models.CharField(max_length=64, verbose_name="操作 ID"),
        ),
        migrations.AlterField(
            model_name="temporarypolicy",
            name="policy_id",
            field=models.BigIntegerField(default=0, verbose_name="后端 policy_id"),
        ),
    ]
