# Generated by Django 2.2.24 on 2021-10-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20201230_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_record_id', models.IntegerField(db_index=True, verbose_name='同步记录id')),
                ('_log', models.TextField(db_column='log', verbose_name='日志详情')),
            ],
        ),
    ]
