# Generated by Django 2.2.24 on 2021-11-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_syncerrorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncrecord',
            options={'ordering': ['-id'], 'verbose_name': '组织架构同步记录', 'verbose_name_plural': '组织架构同步记录'},
        ),
    ]
