# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_subjecttodelete"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentRelationMPTTTree",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tenant_id", models.CharField(default="default", max_length=64, verbose_name="租户 ID")),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="UserLeader",
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["id"], "verbose_name": "部门表", "verbose_name_plural": "部门表"},
        ),
        migrations.AlterModelOptions(
            name="subjecttodelete",
            options={"verbose_name": "待删除的 Subject", "verbose_name_plural": "待删除的 Subject"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["username"], "verbose_name": "用户信息", "verbose_name_plural": "用户信息"},
        ),
        migrations.RemoveField(
            model_name="department",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="department",
            name="order",
        ),
        migrations.RemoveField(
            model_name="departmentmember",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="staff_status",
        ),
        migrations.AddField(
            model_name="department",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="departmentmember",
            name="username",
            field=models.CharField(db_index=True, default="", max_length=255, verbose_name="用户名"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subjecttodelete",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="syncerrorlog",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="syncrecord",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="姓名"),
        ),
        migrations.AddField(
            model_name="user",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="department",
            name="ancestors",
            field=models.TextField(help_text="List[Dict[id,name]] 的 Json 存储", verbose_name="祖先"),
        ),
        migrations.AlterField(
            model_name="department",
            name="child_count",
            field=models.IntegerField(default=0, verbose_name="子部门数量 (非递归)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name="部门 ID"),
        ),
        migrations.AlterField(
            model_name="department",
            name="member_count",
            field=models.IntegerField(default=0, verbose_name="部门下用户数 (非递归)"),
        ),
        migrations.AlterField(
            model_name="department",
            name="recursive_member_count",
            field=models.IntegerField(default=0, verbose_name="(递归) 部门下用户数"),
        ),
        migrations.AlterField(
            model_name="departmentmember",
            name="department_id",
            field=models.IntegerField(db_index=True, verbose_name="部门 ID"),
        ),
        migrations.AlterField(
            model_name="syncerrorlog",
            name="sync_record_id",
            field=models.IntegerField(db_index=True, verbose_name="同步记录 id"),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True, verbose_name="展示名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="用户名"),
        ),
    ]
