# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("long_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtaskstate",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="taskdetail",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="subtaskstate",
            name="celery_id",
            field=models.CharField(max_length=36, verbose_name="celery 任务 id"),
        ),
        migrations.AlterField(
            model_name="subtaskstate",
            name="task_id",
            field=models.IntegerField(verbose_name="父亲任务 id"),
        ),
        migrations.AlterField(
            model_name="taskdetail",
            name="celery_id",
            field=models.CharField(default="", max_length=36, verbose_name="celery 任务 id"),
        ),
    ]
