# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.14 on 2021-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementAPIAllowListConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('api', models.CharField(choices=[('grade_manager_create', '新建分级管理员'), ('grade_manager_update', '更新分级管理员'), ('grade_manager_member_list', '获取分级管理员成员列表'), ('grade_manager_member_add', '添加分级管理员成员'), ('grade_manager_member_delete', '删除分级管理员成员'), ('group_list', '获取用户组列表'), ('group_batch_create', '批量创建用户组'), ('group_update', '更新用户组'), ('group_delete', '删除用户组'), ('group_member_list', '获取用户组成员列表'), ('group_member_add', '添加用户组成员'), ('group_member_delete', '删除用户组成员'), ('group_policy_grant', '授权用户组'), ('user_role_list', '获取用户加入的分级管理员列表')], help_text='*代表任意', max_length=32, verbose_name='API')),
                ('system_id', models.CharField(max_length=32, verbose_name='接入系统')),
            ],
            options={
                'verbose_name': '管理类API允许系统白名单',
                'verbose_name_plural': '管理类API允许系统白名单',
                'ordering': ['-id'],
                'index_together': {('system_id', 'api')},
            },
        ),
    ]
