# Generated by Django 4.2.19 on 2025-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0014_alter_managementapiallowlistconfig_api"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="systemallowauthsystem",
            new_name="management__system__a589b3_idx",
            old_fields=("system_id", "auth_system_id"),
        ),
    ]
