# Generated by Django 3.2.25 on 2026-06-11 10:34

from django.db import migrations

from backend.api.constants import ALLOW_ANY


def init_allow_list(apps, schema_editor):
    """初始化授权API白名单"""
    ManagementAPIAllowListConfig = apps.get_model("management", "ManagementAPIAllowListConfig")

    # 只读取去重所需字段，避免历史 DateTime 数据在不同数据库驱动下发生无关的类型转换错误
    allow_set = set(ManagementAPIAllowListConfig.objects.values_list("system_id", "api"))

    # 白名单列表
    system_id_allow_apis = {
        "bk_aidev": [ALLOW_ANY],
        "auto-ops": [ALLOW_ANY],
        "bk_vision": [ALLOW_ANY],
    }

    # 组装成Model对象
    mgmt_api_allow_list_config = []
    for system_id, apis in system_id_allow_apis.items():
        for api in apis:
            # 已存在，则直接忽略
            if (system_id, api) in allow_set:
                continue
            mgmt_api_allow_list_config.append(ManagementAPIAllowListConfig(system_id=system_id, api=api))
    # 批量创建
    if len(mgmt_api_allow_list_config) != 0:
        ManagementAPIAllowListConfig.objects.bulk_create(mgmt_api_allow_list_config)


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0015_rename_systemallowauthsystem_system_id_auth_system_id_management__system__a589b3_idx",
        ),
    ]

    operations = [migrations.RunPython(init_allow_list)]
