# Generated by Django 3.2.16 on 2023-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512, verbose_name='名称')),
                ('description', models.CharField(max_length=512, verbose_name='描述')),
            ],
            options={
                'verbose_name': '人员模板',
                'verbose_name_plural': '人员模板',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplateRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('template_id', models.IntegerField(verbose_name='模板ID')),
                ('subject_type', models.CharField(max_length=32, verbose_name='类型')),
                ('subject_id', models.CharField(max_length=64, verbose_name='ID')),
            ],
            options={
                'verbose_name': '人员模板关联关系',
                'verbose_name_plural': '人员模板关联关系',
                'ordering': ['-id'],
                'unique_together': {('template_id', 'subject_type', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('template_id', models.IntegerField(verbose_name='模板ID')),
                ('group_id', models.IntegerField(verbose_name='用户组ID')),
                ('expired_at', models.IntegerField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '人员模板用户组关联关系',
                'verbose_name_plural': '人员模板用户组关联关系',
                'ordering': ['-id'],
                'unique_together': {('template_id', 'group_id')},
            },
        ),
    ]
