# Generated by Django 3.2.16 on 2023-11-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttemplategroup',
            name='expired_at',
            field=models.BigIntegerField(verbose_name='过期时间'),
        ),
    ]
