# Generated by Django 3.2.16 on 2023-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_template', '0003_auto_20231110_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttemplate',
            name='source_group_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='来源用户组ID'),
        ),
        migrations.AlterField(
            model_name='subjecttemplategroup',
            name='group_id',
            field=models.IntegerField(db_index=True, verbose_name='用户组ID'),
        ),
        migrations.AlterField(
            model_name='subjecttemplategroup',
            name='template_id',
            field=models.IntegerField(db_index=True, verbose_name='模板ID'),
        ),
        migrations.AlterField(
            model_name='subjecttemplaterelation',
            name='template_id',
            field=models.IntegerField(db_index=True, verbose_name='模板ID'),
        ),
    ]
