# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subject_template", "0004_auto_20231115_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjecttemplate",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="subjecttemplategroup",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="subjecttemplaterelation",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="subjecttemplate",
            name="source_group_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="来源用户组 ID"),
        ),
        migrations.AlterField(
            model_name="subjecttemplategroup",
            name="group_id",
            field=models.IntegerField(db_index=True, verbose_name="用户组 ID"),
        ),
        migrations.AlterField(
            model_name="subjecttemplategroup",
            name="template_id",
            field=models.IntegerField(db_index=True, verbose_name="模板 ID"),
        ),
        migrations.AlterField(
            model_name="subjecttemplaterelation",
            name="template_id",
            field=models.IntegerField(db_index=True, verbose_name="模板 ID"),
        ),
    ]
