# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.10 on 2020-06-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('name_en', models.CharField(default='', max_length=64, verbose_name='英文名')),
                ('code', models.CharField(max_length=64, verbose_name='标志')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('name_en', models.CharField(default='', max_length=128, verbose_name='英文名')),
                ('description', models.CharField(default='', max_length=255, verbose_name='描述')),
                ('type', models.CharField(choices=[('staff', '个人用户'), ('superuser', '超级管理员'), ('system_manager', '系统管理员'), ('rating_manager', '分级管理员')], max_length=32, verbose_name='申请单类型')),
                ('code', models.CharField(default='', max_length=64, verbose_name='标志')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RolePerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('perm_id', models.IntegerField(verbose_name='权限ID')),
            ],
            options={
                'verbose_name': '角色的权限',
                'verbose_name_plural': '角色的权限',
            },
        ),
        migrations.CreateModel(
            name='RoleRelatedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('object_type', models.CharField(choices=[('template', '权限模板'), ('group', '用户组')], max_length=32, verbose_name='对象类型')),
                ('object_id', models.IntegerField(verbose_name='对象ID')),
            ],
            options={
                'verbose_name': '角色关联资源',
                'verbose_name_plural': '角色关联资源',
            },
        ),
        migrations.CreateModel(
            name='RoleScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('type', models.CharField(choices=[('authorization', '系统操作'), ('subject', '授权对象')], max_length=32, verbose_name='限制类型')),
                ('content', models.TextField(verbose_name='限制内容')),
            ],
            options={
                'verbose_name': '角色的限制范围',
                'verbose_name_plural': '角色的限制范围',
            },
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户id')),
                ('is_sync', models.BooleanField(default=False, verbose_name='是否同步到后台')),
            ],
            options={
                'verbose_name': '角色的用户',
                'verbose_name_plural': '角色的用户',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScopeSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_scope_id', models.IntegerField(verbose_name='角色限制ID')),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('subject_type', models.CharField(choices=[('user', '用户'), ('group', '用户组'), ('department', '部门')], max_length=32, verbose_name='授权对象类型')),
                ('subject_id', models.CharField(max_length=64, verbose_name='授权对象ID')),
            ],
            options={
                'verbose_name': 'subject限制',
                'verbose_name_plural': 'subject限制',
            },
        ),
    ]
