# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.14 on 2020-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_auto_20200916_2012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rolerelatedobject',
            unique_together={('role_id', 'object_type', 'object_id')},
        ),
        migrations.AlterIndexTogether(
            name='roleperm',
            index_together={('role_id',)},
        ),
        migrations.AlterIndexTogether(
            name='rolescope',
            index_together={('role_id',)},
        ),
        migrations.AlterIndexTogether(
            name='roleuser',
            index_together={('role_id',)},
        ),
        migrations.CreateModel(
            name='RoleCommonAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('system_id', models.CharField(max_length=32, verbose_name='系统ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('name_en', models.CharField(default='', max_length=128, verbose_name='名称EN')),
                ('_action_ids', models.TextField(db_column='action_ids', verbose_name='操作列表')),
            ],
            options={
                'verbose_name': '角色常用操作',
                'verbose_name_plural': '角色常用操作',
                'ordering': ['id'],
                'index_together': {('role_id', 'system_id')},
            },
        ),
    ]
