# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.16 on 2020-12-30 08:53

from django.db import migrations

from backend.biz.role import RoleBiz


def add_admin_to_super_manager_member(apps, schema_editor):
    """将admin添加到超级管理员里"""
    RoleBiz().add_super_manager_member("admin", True)


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0007_auto_20201209_1437'),
        ('organization', '0004_auto_20201230_1653'),
    ]

    operations = [
        migrations.RunPython(add_admin_to_super_manager_member)
    ]
