# Generated by Django 2.2.28 on 2022-11-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0011_auto_20221027_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='source_system_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='readonly',
            field=models.BooleanField(default=False, verbose_name='只读标识'),
        ),
    ]
