# Generated by Django 2.2.28 on 2022-10-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0011_auto_20221019_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleuser',
            name='readonly',
            field=models.BooleanField(default=False, verbose_name='用户组只读标识'),
        ),
        migrations.AlterField(
            model_name='rolerelation',
            name='role_id',
            field=models.IntegerField(db_index=True, verbose_name='角色ID'),
        ),
    ]
