# Generated by Django 3.2.16 on 2022-12-13 11:41
import json

from django.db import migrations

from backend.service.constants import RoleType


def add_admin_to_super_manager_member(apps, schema_editor):
    """将admin添加到超级管理员里"""
    # Note：这里不能调用add_super_manager_member方法给超级管理员添加admin，因为该方法里会自动向IAM后台同步admin为super role
    #  但有admin用户后台可能还未存在，所以会失败
    #  由于admin的特殊性，IAM后台判断super permission时是先判断是否super user，然后再判断是否super role
    #  所以不向后台将admin添加为super role并不会影响admin的鉴权（admin在后台代码里默认初始化为super user）

    # 使用历史模型，避免访问不存在的字段
    Role = apps.get_model("role", "Role")
    RoleUser = apps.get_model("role", "RoleUser")
    RoleUserSystemPermission = apps.get_model("role", "RoleUserSystemPermission")

    username = "admin"
    role = Role.objects.get(type=RoleType.SUPER_MANAGER.value)
    # 判断是否已存在 - 避免使用role.members属性
    exists = RoleUser.objects.filter(role_id=role.id, username=username).exists()
    if exists:
        return

    # 添加成员
    RoleUser.objects.create(role_id=role.id, username=username)

    # 拥有所有系统的权限
    # 1. 尝试获取现有记录
    obj, created = RoleUserSystemPermission.objects.get_or_create(
        role_id=role.id,
    )

    # 2. 更新enabled_users
    try:
        content_dict = json.loads(obj.content)
    except (json.JSONDecodeError, TypeError):
        # 如果content格式错误，使用模型默认值
        content_dict = {"enabled_users": [], "global_enabled": False}

    # 确保enabled_users是列表
    if not isinstance(content_dict.get("enabled_users"), list):
        content_dict["enabled_users"] = []

    # 如果admin不在列表中，则添加
    if username not in content_dict["enabled_users"]:
        content_dict["enabled_users"].append(username)

    # 更新记录
    obj.content = json.dumps(content_dict)
    obj.save(update_fields=["content", "updated_time"])


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0012_auto_20221110_1511"),
    ]

    operations = [migrations.RunPython(add_admin_to_super_manager_member)]
