# Generated by Django 2.2.28 on 2022-10-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0012_auto_20221026_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='inherit_subject_scope',
            field=models.BooleanField(default=False, verbose_name='继承人员管理范围'),
        ),
    ]
