# Generated by Django 3.2.16 on 2023-05-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0013_auto_20221213_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=512, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name_en',
            field=models.CharField(default='', max_length=512, verbose_name='英文名'),
        ),
    ]
