# Generated by Django 3.2.16 on 2023-07-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0014_auto_20230518_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleResourceRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('system_id', models.CharField(max_length=32, verbose_name='资源系统')),
                ('resource_type_id', models.CharField(max_length=32, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=36, verbose_name='资源ID')),
            ],
            options={
                'verbose_name': '角色资源关系',
                'verbose_name_plural': '角色资源关系',
                'unique_together': {('resource_id', 'resource_type_id', 'system_id', 'role_id')},
            },
        ),
    ]
