# Generated by Django 3.2.16 on 2023-07-20 09:59

from django.db import migrations


def run_migrate_role_resource_label(apps, schema_editor):
    # 使用历史模型，避免依赖当前模型状态
    # 由于 enabled 字段在后续迁移中才添加，这里不能使用 call_command
    # 数据迁移逻辑被延迟到后续迁移中执行
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0015_roleresourcerelation"),
    ]

    operations = [migrations.RunPython(run_migrate_role_resource_label)]
