# Generated by Django 3.2.16 on 2023-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0017_auto_20230818_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterIndexTogether(
            name='scopesubject',
            index_together={('subject_id', 'subject_type', 'role_id')},
        ),
    ]
