# Generated by Django 3.2.16 on 2023-08-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0018_auto_20230822_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolesource',
            options={'verbose_name': '角色创建来源', 'verbose_name_plural': '角色创建来源'},
        ),
        migrations.AlterField(
            model_name='roleusersystempermission',
            name='role_id',
            field=models.IntegerField(db_index=True, verbose_name='角色ID'),
        ),
        migrations.AlterIndexTogether(
            name='rolesource',
            index_together={('source_system_id', 'source_type')},
        ),
    ]
