# Generated by Django 3.2.16 on 2023-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0019_auto_20230824_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('role_id', models.IntegerField(verbose_name='角色ID')),
                ('type', models.CharField(choices=[('group', '用户组配置')], max_length=32, verbose_name='限制类型')),
                ('_config', models.TextField(db_column='config', default='{}', verbose_name='配置')),
            ],
            options={
                'verbose_name': '角色配置',
                'verbose_name_plural': '角色配置',
                'index_together': {('role_id', 'type')},
            },
        ),
    ]
