# Generated by Django 3.2.16 on 2023-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0021_auto_20231117_1659'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='scopesubject',
            index_together={('role_id', 'role_scope_id'), ('subject_id', 'subject_type', 'role_id')},
        ),
    ]
