# Generated by Django 3.2.16 on 2024-03-29 02:55

from django.db import migrations


def delete_periodic_tasks(apps, schema_editor):
    # 获取 PeriodicTask 模型
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    PeriodicTask.objects.filter(name="periodic_user_group_policy_expire_remind").delete()
    PeriodicTask.objects.filter(name="periodic_role_group_expire_remind").delete()
    PeriodicTask.objects.filter(name="check_user_permission_clean_task").delete()
    PeriodicTask.objects.filter(name="clean_user_permission_clean_record").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0023_auto_20240222_1416'),
    ]

    operations = [
        migrations.RunPython(delete_periodic_tasks),
    ]
