# Generated by Django 3.2.25 on 2024-04-07 08:02

from django.db import migrations

from backend.service.constants import RoleType
from backend.util.json import json_dumps


def init_super_manager_notification_config(apps, schema_editor):
    """初始化超级管理员通知设置"""
    Role = apps.get_model('role', 'Role')
    RolePolicyExpiredNotificationConfig = apps.get_model('role', 'RolePolicyExpiredNotificationConfig')

    role = Role.objects.filter(type=RoleType.SUPER_MANAGER.value).first()
    if not role:
        return

    config = RolePolicyExpiredNotificationConfig(role_id=role.id)
    config._config = json_dumps({
        "notification_types": ["mail", "rtx"],
        "send_time": "10:00",
        "expire_days_before": 15,
        "expire_days_after": 1,
        "send_days": ["monday"],
    })
    config.save()


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0025_rolepolicyexpirednotificationconfig'),
    ]

    operations = [migrations.RunPython(init_super_manager_notification_config),]
