# Generated by Django 3.2.25 on 2025-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0026_auto_20240407_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('staff', '个人用户'), ('super_manager', '超级管理员'), ('system_manager', '系统管理员'), ('rating_manager', '管理空间管理员'), ('subset_manager', '二级管理空间管理员')], db_index=True, max_length=32, verbose_name='类型'),
        ),
    ]
