# Generated by Django 4.2.19 on 2025-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("role", "0027_alter_role_type"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rolecommonaction",
            new_name="role_roleco_role_id_b747b6_idx",
            old_fields=("role_id", "system_id"),
        ),
        migrations.RenameIndex(
            model_name="roleconfig",
            new_name="role_roleco_role_id_a0db67_idx",
            old_fields=("role_id", "type"),
        ),
        migrations.RenameIndex(
            model_name="roleperm",
            new_name="role_rolepe_role_id_a7aeba_idx",
            old_fields=("role_id",),
        ),
        migrations.RenameIndex(
            model_name="rolescope",
            new_name="role_rolesc_role_id_6f133b_idx",
            old_fields=("role_id",),
        ),
        migrations.RenameIndex(
            model_name="rolesource",
            new_name="role_roleso_source__40355e_idx",
            old_fields=("source_system_id", "source_type"),
        ),
        migrations.RenameIndex(
            model_name="roleuser",
            new_name="role_roleus_role_id_07838e_idx",
            old_fields=("role_id", "username"),
        ),
        migrations.RenameIndex(
            model_name="scopesubject",
            new_name="role_scopes_role_id_989ca2_idx",
            old_fields=("role_id", "role_scope_id"),
        ),
        migrations.RenameIndex(
            model_name="scopesubject",
            new_name="role_scopes_subject_2cfbb4_idx",
            old_fields=("subject_id", "subject_type", "role_id"),
        ),
    ]
