# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0028_rename_rolecommonaction_role_id_system_id_role_roleco_role_id_b747b6_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scopesubject",
            options={"verbose_name": "subject 限制", "verbose_name_plural": "subject 限制"},
        ),
        migrations.AddField(
            model_name="permission",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="role",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolecommonaction",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="roleconfig",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolegroupmember",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="roleperm",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolepolicyexpirednotificationconfig",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolerelatedobject",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolerelation",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="roleresourcerelation",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolescope",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="rolesource",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="roleuser",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="roleusersystempermission",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="scopesubject",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="rolecommonaction",
            name="name_en",
            field=models.CharField(default="", max_length=128, verbose_name="名称 EN"),
        ),
        migrations.AlterField(
            model_name="rolecommonaction",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolecommonaction",
            name="system_id",
            field=models.CharField(max_length=32, verbose_name="系统 ID"),
        ),
        migrations.AlterField(
            model_name="roleconfig",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolegroupmember",
            name="group_id",
            field=models.IntegerField(db_index=True, verbose_name="用户组 ID"),
        ),
        migrations.AlterField(
            model_name="rolegroupmember",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolegroupmember",
            name="subject_id",
            field=models.CharField(max_length=32, verbose_name="用户 ID"),
        ),
        migrations.AlterField(
            model_name="rolegroupmember",
            name="subject_template_id",
            field=models.IntegerField(db_index=True, default=0, verbose_name="用户模板 ID"),
        ),
        migrations.AlterField(
            model_name="rolegroupmember",
            name="subset_id",
            field=models.IntegerField(default=0, verbose_name="二级角色 ID"),
        ),
        migrations.AlterField(
            model_name="roleperm",
            name="perm_id",
            field=models.IntegerField(verbose_name="权限 ID"),
        ),
        migrations.AlterField(
            model_name="roleperm",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolepolicyexpirednotificationconfig",
            name="role_id",
            field=models.IntegerField(unique=True, verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolerelatedobject",
            name="object_id",
            field=models.IntegerField(verbose_name="对象 ID"),
        ),
        migrations.AlterField(
            model_name="rolerelatedobject",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolerelation",
            name="parent_id",
            field=models.IntegerField(verbose_name="父级角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolerelation",
            name="role_id",
            field=models.IntegerField(db_index=True, verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="roleresourcerelation",
            name="resource_id",
            field=models.CharField(max_length=36, verbose_name="资源 ID"),
        ),
        migrations.AlterField(
            model_name="roleresourcerelation",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolescope",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="rolesource",
            name="role_id",
            field=models.IntegerField(unique=True, verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="roleuser",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="roleuser",
            name="username",
            field=models.CharField(db_index=True, max_length=64, verbose_name="用户 id"),
        ),
        migrations.AlterField(
            model_name="roleusersystempermission",
            name="role_id",
            field=models.IntegerField(db_index=True, verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="scopesubject",
            name="role_id",
            field=models.IntegerField(verbose_name="角色 ID"),
        ),
        migrations.AlterField(
            model_name="scopesubject",
            name="role_scope_id",
            field=models.IntegerField(verbose_name="角色限制 ID"),
        ),
        migrations.AlterField(
            model_name="scopesubject",
            name="subject_id",
            field=models.CharField(max_length=64, verbose_name="授权对象 ID"),
        ),
    ]
