# Generated by Django 3.2.16 on 2022-12-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverrecord',
            name='status',
            field=models.CharField(choices=[('running', '正在交接'), ('succeed', '交接成功'), ('failed', '交接失败'), ('partial_failed', '部分失败')], default='running', max_length=16, verbose_name='交接状态'),
        ),
        migrations.AlterField(
            model_name='handovertask',
            name='object_type',
            field=models.CharField(choices=[('group_ids', '用户组权限'), ('custom_policies', '自定义权限'), ('role_ids', '管理员权限')], max_length=16, verbose_name='权限类别'),
        ),
        migrations.AlterField(
            model_name='handovertask',
            name='status',
            field=models.CharField(choices=[('running', '正在交接'), ('succeed', '交接成功'), ('failed', '交接失败')], default='running', max_length=16, verbose_name='交接状态'),
        ),
    ]
