# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handover", "0003_alter_handovertask_object_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="handoverrecord",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="handovertask",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="handovertask",
            name="handover_record_id",
            field=models.IntegerField(verbose_name="交接记录 ID"),
        ),
        migrations.AlterField(
            model_name="handovertask",
            name="object_id",
            field=models.CharField(max_length=60, verbose_name="交接对象 ID"),
        ),
    ]
