# Generated by Django 3.2.16 on 2023-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220901_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='_favorite_systems',
            field=models.TextField(default='[]', verbose_name='收藏的系统'),
        ),
    ]
