# Generated by Django 3.2.25 on 2025-08-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile__favorite_systems'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissioncleanuprecord',
            name='clean_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='清理时间'),
        ),
    ]
