# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_userprofile__favorite_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpermissioncleanuprecord",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
    ]
