# Generated by Django 2.2.25 on 2022-04-12 08:27

from django.db import migrations

from backend.apps.action.tasks import generate_action_aggregate


def genarate_new_aggregate_action(apps, schema_editor):
    AggregateAction = apps.get_model("action", "AggregateAction")
    AggregateAction.objects.all().delete()

    generate_action_aggregate()


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0005_auto_20210407_2013"),
    ]

    operations = [
        migrations.RunPython(genarate_new_aggregate_action),
    ]
