# Generated by Django 4.2.19 on 2025-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0006_auto_20220412_1627"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aggregateaction",
            new_name="action_aggr_system__009ba6_idx",
            old_fields=("system_id",),
        ),
    ]
