# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.10 on 2020-03-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updater', models.CharField(max_length=32, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='模板名称')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('system_id', models.CharField(max_length=32, verbose_name='系统ID')),
                ('description', models.CharField(default='', max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限模板',
                'verbose_name_plural': '权限模板',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PermTemplatePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField(verbose_name='模板ID')),
                ('version', models.SmallIntegerField(default=1, verbose_name='版本')),
                ('_data', models.TextField(db_column='data', verbose_name='申请数据')),
            ],
            options={
                'verbose_name': '权限模板策略',
                'verbose_name_plural': '权限模板策略',
            },
        ),
        migrations.CreateModel(
            name='PermTemplatePolicyAuthorized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updater', models.CharField(max_length=32, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('template_id', models.IntegerField(verbose_name='模板ID')),
                ('version', models.SmallIntegerField(default=1, verbose_name='版本')),
                ('subject_type', models.CharField(choices=[('user', '用户'), ('group', '用户组'), ('department', '部门')], max_length=32, verbose_name='授权对象类型')),
                ('subject_id', models.CharField(max_length=64, verbose_name='授权对象ID')),
                ('system_id', models.CharField(max_length=32, verbose_name='系统ID')),
                ('expired_at', models.IntegerField(default=0, verbose_name='过期时间戳')),
            ],
            options={
                'verbose_name': '权限模板授权',
                'verbose_name_plural': '权限模板授权',
            },
        ),
    ]
