# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.14 on 2021-03-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_auto_20210312_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermTemplatePreUpdateLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('template_id', models.IntegerField(verbose_name='模板ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('wating', '等待中')], default='wating', max_length=32, verbose_name='类型')),
                ('_action_ids', models.TextField(db_column='action_ids', verbose_name='操作列表')),
            ],
            options={
                'verbose_name': '权限模板更新预提交',
                'verbose_name_plural': '权限模板更新预提交',
                'ordering': ['-created_time'],
                'unique_together': {('template_id',)},
            },
        ),
        migrations.CreateModel(
            name='PermTemplatePreGroupSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('template_id', models.IntegerField(verbose_name='模板ID')),
                ('group_id', models.IntegerField(verbose_name='模板ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('wating', '等待中')], default='wating', max_length=32, verbose_name='类型')),
                ('_data', models.TextField(db_column='data', verbose_name='授权数据')),
            ],
            options={
                'verbose_name': '权限模板更新用户组同步预提交',
                'verbose_name_plural': '权限模板更新用户组同步预提交',
                'ordering': ['-updated_time'],
                'unique_together': {('template_id', 'group_id')},
            },
        ),
    ]
