# Generated by Django 2.2.28 on 2022-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0012_auto_20210330_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='permtemplatepolicyauthorized',
            name='_auth_types',
            field=models.TextField(db_column='auth_types', default='{}', help_text="JSON存储 {'action_id': auth_type, ...}", verbose_name='模板授权策略的鉴权类型'),
        ),
    ]
