# Generated by Django 4.2.19 on 2025-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0014_auto_20221102_1655"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="permtemplate",
            new_name="template_pe_system__823dd9_idx",
            old_fields=("system_id",),
        ),
        migrations.RenameIndex(
            model_name="permtemplatepolicyauthorized",
            new_name="template_pe_system__cfab9a_idx",
            old_fields=("system_id",),
        ),
    ]
