# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0015_rename_permtemplate_system_id_template_pe_system__823dd9_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permtemplate",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="permtemplatepolicyauthorized",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="permtemplatepregroupsync",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AddField(
            model_name="permtemplatepreupdatelock",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplate",
            name="system_id",
            field=models.CharField(max_length=32, verbose_name="系统 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplatepolicyauthorized",
            name="_auth_types",
            field=models.TextField(
                db_column="auth_types",
                default="{}",
                help_text="JSON 存储 {'action_id': auth_type, ...}",
                verbose_name="模板授权策略的鉴权类型",
            ),
        ),
        migrations.AlterField(
            model_name="permtemplatepolicyauthorized",
            name="subject_id",
            field=models.CharField(max_length=64, verbose_name="授权对象 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplatepolicyauthorized",
            name="system_id",
            field=models.CharField(max_length=32, verbose_name="系统 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplatepolicyauthorized",
            name="template_id",
            field=models.IntegerField(verbose_name="模板 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplatepregroupsync",
            name="group_id",
            field=models.IntegerField(verbose_name="模板 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplatepregroupsync",
            name="template_id",
            field=models.IntegerField(verbose_name="模板 ID"),
        ),
        migrations.AlterField(
            model_name="permtemplatepreupdatelock",
            name="template_id",
            field=models.IntegerField(verbose_name="模板 ID"),
        ),
    ]
