# Generated by Django 3.2.16 on 2023-03-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=64, verbose_name='项目ID')),
                ('type', models.CharField(default='', max_length=32, verbose_name='数据类型')),
                ('data', models.TextField(verbose_name='数据')),
            ],
            options={
                'verbose_name': '迁移数据',
                'verbose_name_plural': '迁移数据',
            },
        ),
        migrations.CreateModel(
            name='MigrateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=36, verbose_name='任务状态')),
                ('celery_id', models.CharField(default='', max_length=36, verbose_name='celery任务id')),
            ],
            options={
                'verbose_name': '迁移任务',
                'verbose_name_plural': '迁移任务',
            },
        ),
    ]
