# Generated by Django 3.2.16 on 2023-03-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkci', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migratetask',
            name='celery_id',
        ),
        migrations.AddField(
            model_name='migratetask',
            name='role_ids',
            field=models.TextField(default='', verbose_name='role_ids'),
        ),
    ]
