# Generated by Django 3.2.16 on 2023-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkci', '0002_auto_20230322_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrateLegacyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=36, verbose_name='任务状态')),
                ('project_ids', models.TextField(default='', verbose_name='project_ids')),
            ],
            options={
                'verbose_name': '迁移任务',
                'verbose_name_plural': '迁移任务',
            },
        ),
        migrations.AddField(
            model_name='migratedata',
            name='version',
            field=models.CharField(default='v3', max_length=32, verbose_name='版本'),
        ),
    ]
