# Generated by Django 4.2 on 2025-03-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bkci', '0003_auto_20230420_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('policy_id', models.PositiveIntegerField(blank=True, null=True)),
                ('role_id', models.PositiveIntegerField(blank=True, null=True)),
                ('project_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('effect', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_code', models.CharField(max_length=127)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'policy_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_app_id', models.PositiveIntegerField(blank=True, null=True)),
                ('project_code', models.CharField(blank=True, max_length=32, null=True)),
                ('env', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=32, null=True)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_code', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_type_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_type_code', models.CharField(blank=True, max_length=16, null=True)),
                ('resource_type_name', models.CharField(blank=True, max_length=64, null=True)),
                ('service_id', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resource_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=32, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role_name', models.CharField(blank=True, max_length=127, null=True)),
                ('type', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('service_code', models.CharField(blank=True, max_length=16, null=True)),
                ('service_name', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled_envs', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=32, null=True)),
                ('role_id', models.PositiveIntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
    ]
