# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.16 on 2021-01-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAPIAllowListConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64, verbose_name='创建者')),
                ('updater', models.CharField(max_length=64, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('authorization_instance', '实例授权'), ('creator_authorization_instance', '新建关联实例授权')], max_length=32, verbose_name='API类型')),
                ('system_id', models.CharField(max_length=32, verbose_name='接入系统')),
                ('object_id', models.CharField(help_text='*代表任意', max_length=32, verbose_name='资源类型或操作ID')),
            ],
            options={
                'verbose_name': '授权API白名单配置',
                'verbose_name_plural': '授权API白名单配置',
                'ordering': ['-id'],
                'index_together': {('system_id', 'object_id')},
            },
        ),
    ]
