# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.16 on 2021-01-11 12:13

from django.db import migrations

from backend.api.authorization.constants import AuthorizationAPIEnum
from backend.api.constants import ALLOW_ANY


def init_allow_list(apps, schema_editor):
    """初始化授权API白名单"""
    AuthAPIAllowListConfig = apps.get_model("authorization", "AuthAPIAllowListConfig")
    # 实例授权API 白名单
    system_ids = ["bk_bkdata", "bk_monitorv3", "idata-web", "ace"]
    # 新建关联实例授权API 白名单
    system_resource_types = {
        "bk_paas": ["app"],
        "bk_usermgr": ["category"],
        "bk_cmdb": [
            "sys_resource_pool_directory",
            "biz",
            "sys_cloud_account",
            "sys_cloud_resource_task",
            "sys_cloud_area",
            "sys_event_pushing",
            "sys_model_group",
            "sys_model",
            "sys_association_type",
            "biz_process_service_template",
            "biz_set_template",
            "biz_custom_query",
        ],
        "bk_job": ["job_template", "job_plan", "script", "cron", "account", "tag"],
        "bk_sops": ["project", "flow", "mini_app", "periodic_task", "task", "common_flow"],
        "bk_ci": ["project", "pipeline", "repertory", "credential", "environment", "env_node", "cert", "codecc_task"],
        "bk_repo": ["project", "repo"],
        "bk_bcs_app": ["project"],
        "bk_log_search": ["collection", "indices", "es_source"],
        "bk_itsm": ["project", "service", "workflow", "flow_version", "role"],
        "bk_nodeman": ["ap", "cloud"],
        "bk_gsekit": ["config_template"],
    }
    auth_api_allow_list_config = [
        AuthAPIAllowListConfig(
            type=AuthorizationAPIEnum.AUTHORIZATION_INSTANCE.value,
            system_id=system_id,
            object_id=ALLOW_ANY
        )
        for system_id in system_ids
    ]
    for system_id, resource_types in system_resource_types.items():
        for resource_type_id in resource_types:
            auth_api_allow_list_config.append(
                AuthAPIAllowListConfig(
                    type=AuthorizationAPIEnum.CREATOR_AUTHORIZATION_INSTANCE.value,
                    system_id=system_id,
                    object_id=resource_type_id
                )
            )
    AuthAPIAllowListConfig.objects.bulk_create(auth_api_allow_list_config)


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_allow_list)
    ]
