# Generated by Django 2.2.24 on 2022-01-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20220120_1502'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='authapiallowlistconfig',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='authapiallowlistconfig',
            unique_together={('system_id', 'object_id')},
        ),

    ]
