# Generated by Django 2.2.28 on 2022-06-01 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20220125_1711'),
    ]

    operations = [
    ]
