# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.28 on 2022-11-01 04:16

from django.db import migrations

from backend.api.authorization.constants import AuthorizationAPIEnum


def init_allow_list(apps, schema_editor):
    """初始化授权API白名单"""
    AuthAPIAllowListConfig = apps.get_model("authorization", "AuthAPIAllowListConfig")
    # 查询已存在白名单，避免重复
    all_allow_list = AuthAPIAllowListConfig.objects.all()
    allow_set = set([(a.type, a.system_id, a.object_id) for a in all_allow_list])
    # 新建关联实例授权API 白名单
    system_resource_types = {
        "bk_monitorv3": ["space"],
    }
    auth_api_allow_list_config = []
    for system_id, resource_types in system_resource_types.items():
        for resource_type_id in resource_types:
            # 已存在，则直接忽略
            if (AuthorizationAPIEnum.CREATOR_AUTHORIZATION_INSTANCE.value, system_id, resource_type_id) in allow_set:
                continue
            auth_api_allow_list_config.append(
                AuthAPIAllowListConfig(
                    type=AuthorizationAPIEnum.CREATOR_AUTHORIZATION_INSTANCE.value,
                    system_id=system_id,
                    object_id=resource_type_id,
                )
            )
    if len(auth_api_allow_list_config) != 0:
        AuthAPIAllowListConfig.objects.bulk_create(auth_api_allow_list_config)


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0012_auto_20220920_1115"),
    ]

    operations = [migrations.RunPython(init_allow_list)]
