# Generated by Django 3.2.25 on 2025-12-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20231128_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authapiallowlistconfig',
            name='type',
            field=models.CharField(choices=[('authorization_instance', '实例授权'), ('creator_authorization_instance', '新建关联实例授权'), ('authorization_attribute', '属性授权')], max_length=32, verbose_name='API类型'),
        ),
        migrations.AlterUniqueTogether(
            name='authapiallowlistconfig',
            unique_together={('system_id', 'object_id', 'type')},
        ),
        migrations.AlterIndexTogether(
            name='authapiallowlistconfig',
            index_together=set(),
        ),
    ]
