# Generated by Django 4.2 on 2025-03-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20231128_1444'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='authapiallowlistconfig',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='authapiallowlistconfig',
            unique_together={('system_id', 'object_id')},
        ),
    ]
