# Generated by Django 3.2.25 on 2025-12-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20231128_1444'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='authapiallowlistconfig',
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='authapiallowlistconfig',
            unique_together={('system_id', 'object_id')},
        ),
    ]

