# Generated by Django 4.2.20 on 2025-12-16 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0017_alter_authapiallowlistconfig_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="authapiallowlistconfig",
            unique_together={("system_id", "object_id", "type")},
        ),
    ]
