# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.10 on 2020-02-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [  # type: ignore
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updater', models.CharField(max_length=32, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, verbose_name='申请单号')),
                ('title', models.CharField(max_length=128, verbose_name='申请单标题')),
                ('type', models.IntegerField(choices=[(1, '按系统申请'), (2, '加入用户组')], verbose_name='申请单类型')),
                ('applicant', models.CharField(max_length=32, verbose_name='申请人')),
                ('reason', models.CharField(default='', max_length=255, verbose_name='申请理由')),
                ('_data', models.TextField(db_column='data', verbose_name='申请数据')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '待审批'), (2, '已批准'), (3, '已拒绝'), (4, '已取消')], default=1, verbose_name='申请状态')),
            ],
            options={
                'verbose_name': '权限申请',
                'verbose_name_plural': '权限申请',
                'ordering': ['-updated_time'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField(verbose_name='申请单ID')),
                ('node_id', models.IntegerField(verbose_name='节点ID')),
                ('approver', models.CharField(max_length=32, null=True, verbose_name='审批人')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '待审批'), (2, '已批准'), (3, '已拒绝'), (4, '已取消')], verbose_name='审批状态')),
            ],
            options={
                'verbose_name': '审批单',
                'verbose_name_plural': '审批单',
            },
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=32, verbose_name='创建者')),
                ('updater', models.CharField(max_length=32, verbose_name='更新者')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('application_id', models.IntegerField(verbose_name='申请单ID')),
                ('index_id', models.IntegerField(verbose_name='排序索引')),
                ('type', models.IntegerField(choices=[(1, '超级管理员'), (2, '直接上级'), (3, '指定审批人')], verbose_name='审批类型')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '待审批'), (2, '已批准'), (3, '已拒绝'), (4, '已取消')], verbose_name='审批状态')),
                ('approver', models.CharField(default='', max_length=32, verbose_name='审批人')),
                ('processing_time', models.DateTimeField(default=None, null=True, verbose_name='审批时间')),
                ('reason', models.CharField(default='', max_length=100, verbose_name='审批意见')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['index_id'],
            },
        ),
    ]
