# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.16 on 2020-11-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200902_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalForm',
        ),
        migrations.DeleteModel(
            name='ApprovalNode',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='code',
            new_name='sn',
        ),
        migrations.RemoveField(
            model_name='application',
            name='_subjects',
        ),
        migrations.AddField(
            model_name='application',
            name='callback_id',
            field=models.CharField(default='', max_length=32, verbose_name='回调随机数ID'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '审批中'), ('pass', '通过'), ('reject', '拒绝'), ('cancelled', '已取消')], default='pending', max_length=32, verbose_name='单据状态'),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('grant_action', '自定义权限申请'), ('join_group', '加入用户组'), ('join_rating_manager', '加入分级管理员'), ('create_rating_manager', '创建或分级管理员'), ('update_rating_manager', '修改分级管理员')], max_length=64, verbose_name='申请单类型'),
        ),
    ]
