# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-权限中心(BlueKing-IAM) available.
Copyright (C) 2017-2021 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 2.2.16 on 2020-12-21 07:56

from django.db import migrations


def delete_old_application(apps, schema_editor):
    """申请对接ITSM后，整个申请单据结构都变化了，需要将之前的删除"""
    Application = apps.get_model("application", "Application")

    # 查询SN不满足ITSM的
    Application.objects.exclude(sn__startswith="REQ").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201109_1717'),
    ]

    operations = [
        migrations.RunPython(delete_old_application)
    ]
