# Generated by Django 2.2.28 on 2022-11-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_auto_20210302_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='source_system_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('grant_action', '自定义权限申请'), ('renew_action', '自定义权限续期'), ('join_group', '加入用户组'), ('renew_group', '用户组续期'), ('join_rating_manager', '加入分级管理员'), ('create_rating_manager', '创建分级管理员'), ('update_rating_manager', '修改分级管理员'), ('grant_temporary_action', '临时权限申请')], max_length=64, verbose_name='申请单类型'),
        ),
    ]
