# Generated by Django 3.2.16 on 2023-08-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20221110_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('grant_action', '自定义权限申请'), ('renew_action', '自定义权限续期'), ('join_group', '加入用户组'), ('renew_group', '用户组续期'), ('join_rating_manager', '加入管理空间'), ('create_rating_manager', '创建管理空间'), ('update_rating_manager', '修改管理空间'), ('grant_temporary_action', '临时权限申请')], max_length=64, verbose_name='申请单类型'),
        ),
    ]
