# Generated by Django 3.2.16 on 2023-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20230822_1227'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='application',
            index_together={('created_time',), ('callback_id', 'sn')},
        ),
    ]
