# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0016_rename_application_created_time_application_created_ca3f79_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="application",
            name="callback_id",
            field=models.CharField(default="", max_length=32, verbose_name="回调随机数 ID"),
        ),
    ]
