# Generated by Django 4.2.20 on 2025-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0016_rename_application_created_time_application_created_ca3f79_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ticket_id",
            field=models.CharField(default="", max_length=32, verbose_name="单据id"),
        ),
    ]
