# Generated by Django 2.2.24 on 2021-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0007_delete_attachpolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='_environment',
        ),
        migrations.AlterField(
            model_name='policy',
            name='action_type',
            field=models.CharField(default='', max_length=32, verbose_name='操作类型'),
        ),
    ]
