# Generated by Django 2.2.28 on 2022-07-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_policy_auth_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_id',
        ),
    ]
