# Generated by Django 4.2.19 on 2025-04-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy", "0011_alter_policy_index_together"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="policy",
            new_name="policy_poli_subject_af7a6a_idx",
            old_fields=("subject_id", "subject_type", "system_id"),
        ),
        migrations.RenameIndex(
            model_name="policy",
            new_name="policy_poli_action__053767_idx",
            old_fields=("action_id", "system_id", "subject_type", "subject_id"),
        ),
    ]
