# Generated by Django 4.2.20 on 2025-07-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policy", "0012_rename_policy_subject_id_subject_type_system_id_policy_poli_subject_af7a6a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="tenant_id",
            field=models.CharField(default="default", max_length=64, verbose_name="租户 ID"),
        ),
        migrations.AlterField(
            model_name="policy",
            name="action_id",
            field=models.CharField(max_length=64, verbose_name="操作 ID"),
        ),
    ]
